version: v2

agents:
  # ===========================================================================
  # Tier 0: Read-Only (comment only)
  # ===========================================================================

  code-reviewer:
    enabled: true
    triggers:
      - type: on-pr
    priority: 1
    policy:
      mode: comment_only
    params:
      review_types:
        - security
        - performance
        - bugs
        - python-best-practices
        - async-patterns
      max_comments: 15
      severity_threshold: warning
      focus_areas:
        - "apps/api/**"
        - "packages/core/**"

  security-scanner:
    enabled: true
    triggers:
      - type: on-pr
      - type: nightly
    priority: 1
    policy:
      mode: comment_only
    params:
      scan_types:
        - secrets
        - vulnerabilities
        - sql-injection
        - dependency-vulnerabilities
      fail_on_critical: true
      # Extra important for a code indexing tool
      check_for:
        - hardcoded_credentials
        - api_keys
        - database_urls

  # ===========================================================================
  # Tier 1: Low Risk (can direct commit or PR, no auto-merge)
  # ===========================================================================

  linter-fixer:
    enabled: true
    triggers:
      - type: on-pr
    priority: 2
    policy:
      mode: pr
      auto_merge: false
    conditions:
      paths:
        include:
          - "**/*.py"
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.js"
        exclude:
          - "*_pb2.py"
          - "*_pb2.pyi"
          - "**/proto/**"
    params:
      tools:
        python:
          - ruff
        typescript:
          - eslint
      auto_fix_only: true

  # ===========================================================================
  # Tier 2: Medium Risk (PR required, no auto-merge)
  # ===========================================================================

  documentation:
    enabled: true
    triggers:
      - type: on-merge
    priority: 3
    policy:
      mode: pr
      auto_merge: false
    conditions:
      paths:
        include:
          - "apps/api/src/**"
          - "packages/core/**/*.py"
          - "apps/web/src/**"
        exclude:
          - "**/*_test.py"
          - "**/tests/**"
    params:
      formats:
        - markdown
      update_readme: true
      generate_api_docs: true
      doc_paths:
        - "docs/"
        - "README.md"
        - "CLAUDE.md"

  test-generator:
    enabled: true
    triggers:
      - type: on-pr
    priority: 4
    policy:
      mode: pr
      auto_merge: false
    conditions:
      paths:
        include:
          - "apps/api/src/**/*.py"
          - "packages/core/**/*.py"
        exclude:
          - "**/*_test.py"
          - "**/tests/**"
          - "**/conftest.py"
    params:
      framework: pytest
      coverage_target: 80
      test_style: pytest-asyncio
      fixtures_file: conftest.py

  changelog-generator:
    enabled: true
    triggers:
      - type: on-merge
    priority: 5
    policy:
      mode: pr
      auto_merge: false
    params:
      format: keepachangelog
      include_breaking_changes: true
      categories:
        - Added
        - Changed
        - Fixed
        - Security
        - Deprecated

  # ===========================================================================
  # Tier 3: High Risk (PR required, auto-merge needs checks)
  # ===========================================================================

  dependency-upgrader:
    enabled: true
    triggers:
      - type: nightly
        cron: "0 4 * * 1"  # Monday 4am UTC
    priority: 10
    policy:
      mode: pr
      auto_merge: true
      require_checks:
        - "Lint & Type Check"
        - "Test"
    params:
      ecosystems:
        - pip
        - npm
      major_updates: false
      security_only: false
      group_updates: true
      ignore:
        # Pin specific versions if needed
        # - package: "some-package"
        #   versions: ["2.x"]
