version: v2

agents:
  # ===========================================================================
  # Tier 2: Medium Risk (PR required, no auto-merge)
  # ===========================================================================

  sonarqube-issue-fixer:
    enabled: true
    triggers:
      - type: nightly
        cron: "0 3 * * *"  # Daily 3am UTC
    priority: 1
    policy:
      mode: pr
      auto_merge: false
    params:
      sonar_project_key: contextmine
      fix_types:
        - bugs
        - code_smells
        - vulnerabilities
      severity_threshold: major  # major, minor, critical, blocker
      max_issues_per_run: 10
      exclude_rules:
        # Add rule IDs to skip if needed
        # - "python:S1066"

  documentation:
    enabled: true
    triggers:
      - type: on-merge
    priority: 3
    policy:
      mode: pr
      auto_merge: false
    conditions:
      paths:
        include:
          - "apps/api/src/**"
          - "packages/core/**/*.py"
          - "apps/web/src/**"
        exclude:
          - "**/*_test.py"
          - "**/tests/**"
    params:
      formats:
        - markdown
      update_readme: true
      generate_api_docs: true
      doc_paths:
        - "docs/"
        - "README.md"
        - "CLAUDE.md"

  test-generator:
    enabled: true
    triggers:
      - type: on-pr
    priority: 4
    policy:
      mode: pr
      auto_merge: false
    conditions:
      paths:
        include:
          - "apps/api/src/**/*.py"
          - "packages/core/**/*.py"
        exclude:
          - "**/*_test.py"
          - "**/tests/**"
          - "**/conftest.py"
    params:
      framework: pytest
      coverage_target: 80
      test_style: pytest-asyncio
      fixtures_file: conftest.py

  changelog-generator:
    enabled: true
    triggers:
      - type: on-merge
    priority: 5
    policy:
      mode: pr
      auto_merge: false
    params:
      format: keepachangelog
      include_breaking_changes: true
      categories:
        - Added
        - Changed
        - Fixed
        - Security
        - Deprecated

  # ===========================================================================
  # Tier 3: High Risk (PR required, auto-merge needs checks)
  # ===========================================================================

  dependency-upgrader:
    enabled: true
    triggers:
      - type: nightly
        cron: "0 4 * * 1"  # Monday 4am UTC
    priority: 10
    policy:
      mode: pr
      auto_merge: true
      require_checks:
        - "Lint & Type Check"
        - "Test"
    params:
      ecosystems:
        - pip
        - npm
      major_updates: false
      security_only: false
      group_updates: true
