"""LLM-based entity and relationship extraction for GraphRAG.

This module implements the entity/relationship extraction from the Microsoft
GraphRAG paper "From Local to Global: A Graph RAG Approach to Query-Focused
Summarization".

Instead of relying on syntactic symbols from tree-sitter (which can't understand
that User, Account, Member are semantically related), we use LLM to extract:

1. Semantic entities (domain concepts, not just code symbols)
2. Relationships between entities
3. Entity descriptions for later summarization

The extracted entities form the basis for Leiden community detection.
"""

from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any
from uuid import UUID

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from contextmine_core.research.llm import LLMProvider
    from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

LOW_SIGNAL_REPO_PATH_PARTS = frozenset(
    {
        "node_modules",
        "vendor",
        "dist",
        "build",
        "coverage",
        "__pycache__",
        ".git",
        "venv",
        ".venv",
        "__snapshots__",
        "__fixtures__",
        "fixtures",
    }
)

LOW_SIGNAL_TEST_PATH_PARTS = frozenset(
    {
        "test",
        "tests",
        "__tests__",
        "spec",
        "specs",
    }
)

LOW_SIGNAL_FILE_SUFFIXES = (
    ".min.js",
    ".min.css",
    ".bundle.js",
    ".snap",
    ".lock",
)

LOW_SIGNAL_CONTENT_MARKERS = (
    "@generated",
    "@auto-generated",
    "auto-generated",
    "automatically generated",
    "generated by",
    "do not edit",
    "code coverage generated by",
    "jest snapshot",
    "vitest snapshot",
    "snapshot name:",
)

CONFIG_FILE_SUFFIXES = frozenset(
    {
        ".yaml",
        ".yml",
        ".json",
        ".jsonc",
        ".toml",
        ".ini",
        ".cfg",
        ".conf",
        ".env",
        ".properties",
        ".tf",
        ".tfvars",
        ".sql",
    }
)

DOCUMENTATION_FILE_SUFFIXES = frozenset(
    {
        ".md",
        ".mdx",
        ".rst",
        ".txt",
        ".adoc",
    }
)

CONFIG_FILE_NAMES = frozenset(
    {
        "dockerfile",
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yaml",
        "compose.yml",
        "package.json",
        "package-lock.json",
        "pnpm-lock.yaml",
        "yarn.lock",
        "pyproject.toml",
        "poetry.lock",
        "requirements.txt",
        "requirements-dev.txt",
        "helmfile.yaml",
        "helmfile.yml",
        "chart.yaml",
        "values.yaml",
        "values.yml",
        ".env",
    }
)

CONFIG_PATH_MARKERS = frozenset(
    {
        "k8s",
        "kubernetes",
        "helm",
        "terraform",
        "deploy",
        "deployment",
        "compose",
        "config",
        ".github",
        "workflows",
    }
)


# -----------------------------------------------------------------------------
# Pydantic schemas for structured LLM output
# -----------------------------------------------------------------------------


class ExtractedEntity(BaseModel):
    """An entity extracted from code by LLM."""

    name: str = Field(
        description="Canonical name for this entity (e.g., 'User Authentication', 'Payment Processing')"
    )
    type: str = Field(
        description="Entity type: CONCEPT, COMPONENT, DATA_MODEL, PATTERN, SERVICE, or OTHER"
    )
    description: str = Field(description="Brief description of what this entity represents")
    aliases: list[str] = Field(
        default_factory=list,
        description="Alternative names/symbols that refer to this entity (e.g., ['User', 'Account', 'Member'])",
    )
    source_symbols: list[str] = Field(
        default_factory=list,
        description="Code symbols (class/function names) associated with this entity",
    )
    source_files: list[str] = Field(
        default_factory=list,
        description="Source document or file URIs where this entity was found",
    )


class ExtractedRelationship(BaseModel):
    """A relationship between entities extracted by LLM."""

    source: str = Field(description="Source entity name")
    target: str = Field(description="Target entity name")
    relationship: str = Field(
        description="Type of relationship: USES, CONTAINS, DEPENDS_ON, IMPLEMENTS, VALIDATES, TRANSFORMS, CALLS, or OTHER"
    )
    description: str = Field(description="Brief description of the relationship")
    strength: float = Field(ge=0, le=1, description="Relationship strength (0-1)")


class ExtractionResult(BaseModel):
    """Complete extraction result from a code chunk."""

    entities: list[ExtractedEntity] = Field(default_factory=list)
    relationships: list[ExtractedRelationship] = Field(default_factory=list)


# -----------------------------------------------------------------------------
# Extraction prompts
# -----------------------------------------------------------------------------

ENTITY_EXTRACTION_SYSTEM = """You are a code analyst extracting durable architecture and domain entities from source code.

Your task is to identify high-signal DOMAIN CONCEPTS, COMPONENTS, DATA MODELS, SERVICES,
and design PATTERNS that help explain how the system works.

For example, if you see classes named User, Account, Member, AuthService, LoginController:
- Extract ONE entity called "User Authentication" or "Identity Management"
- List User, Account, Member, AuthService, LoginController as source_symbols
- List "user", "account", "member", "auth" as aliases

Entity types:
- CONCEPT: Domain concepts (authentication, payment processing, data validation)
- COMPONENT: Architectural components (API layer, cache service, message queue)
- DATA_MODEL: Core data entities (User, Order, Product - the domain model)
- PATTERN: Design patterns (Repository, Factory, Observer)
- SERVICE: External services or integrations (email service, payment gateway)
- OTHER: Anything else significant

Focus on SEMANTIC meaning, not syntactic structure. Group related symbols into single entities.

Ignore low-signal code such as:
- tests, mocks, fixtures, snapshots, and test harness setup
- generated code, vendored dependencies, build output, minified bundles
- framework boilerplate, import/export barrels, trivial DTO/schema wrappers
- generic helper names unless they represent a real subsystem

Prefer returning 0-5 high-signal entities. If the chunk is mostly boilerplate or has no durable concepts,
return an empty entities array."""

ENTITY_EXTRACTION_PROMPT = """Analyze this code and extract semantic entities.

FILE PATH: {file_path}
LANGUAGE: {language}
LINES: {start_line}-{end_line}

EXTRACTION GOAL:
- {focus_guidance}

CODE:
```
{code}
```

Extract entities that represent meaningful domain concepts. Group related code symbols
(classes, functions, variables) into single semantic entities.

Remember:
- User, Account, Member, Profile might all be ONE entity "User Management"
- authenticate(), login(), validatePassword() might all be ONE entity "Authentication"
- OrderService, OrderRepository, OrderController might all be ONE entity "Order Processing"

Return a JSON object with 'entities' array."""

RELATIONSHIP_EXTRACTION_SYSTEM = """You are a code analyst extracting relationships between durable domain and architecture entities.

Given a list of entities and the code they came from, identify how entities relate to each other.

Relationship types:
- USES: Entity A uses/calls Entity B
- CONTAINS: Entity A contains/owns Entity B
- DEPENDS_ON: Entity A depends on Entity B
- IMPLEMENTS: Entity A implements/realizes Entity B
- VALIDATES: Entity A validates Entity B
- TRANSFORMS: Entity A transforms/converts Entity B
- CALLS: Entity A invokes Entity B
- OTHER: Other significant relationship

Focus on SEMANTIC relationships between domain concepts, not just code-level function calls.

Ignore incidental test/framework wiring. Only emit relationships that reflect durable behavior,
ownership, dependency, validation, transformation, or architectural coupling."""

RELATIONSHIP_EXTRACTION_PROMPT = """Given these entities extracted from code, identify relationships between them.

FILE PATH: {file_path}
LANGUAGE: {language}
LINES: {start_line}-{end_line}

ENTITIES:
{entities}

CODE CONTEXT:
```
{code}
```

Identify meaningful relationships between the entities. Focus on domain-level relationships,
not just which function calls which. If the chunk only contains boilerplate/test setup,
return no relationships.

RELATIONSHIP FOCUS:
- {relationship_focus}

Return a JSON object with 'relationships' array."""


# -----------------------------------------------------------------------------
# Dataclasses for internal use
# -----------------------------------------------------------------------------


@dataclass
class SemanticEntity:
    """A semantic entity for the knowledge graph."""

    id: str  # Hash-based ID
    name: str
    entity_type: str
    description: str
    aliases: list[str] = field(default_factory=list)
    source_symbols: list[str] = field(default_factory=list)
    source_files: list[str] = field(default_factory=list)

    @property
    def natural_key(self) -> str:
        """Natural key for deduplication."""
        return f"entity:{self.name.lower().replace(' ', '_')}"


@dataclass
class SemanticRelationship:
    """A semantic relationship between entities."""

    source_entity: str  # Entity name
    target_entity: str  # Entity name
    relationship_type: str
    description: str
    strength: float = 1.0


@dataclass
class EntityEvidenceRecord:
    """Evidence record for a semantic entity mention in a chunk."""

    file_path: str
    chunk_id: UUID | None = None
    start_line: int = 1
    end_line: int = 1
    snippet: str | None = None


@dataclass
class ExtractionBatch:
    """Result of extracting from multiple code chunks."""

    entities: list[SemanticEntity] = field(default_factory=list)
    relationships: list[SemanticRelationship] = field(default_factory=list)
    chunks_processed: int = 0
    errors: list[str] = field(default_factory=list)

    # Track which entities appear in which documents (for cross-doc relationships)
    # document_uri -> list of entity names (before resolution)
    entity_occurrences: dict[str, list[str]] = field(default_factory=dict)
    # canonical entity name -> chunk/file evidence records
    entity_evidence: dict[str, list[EntityEvidenceRecord]] = field(default_factory=dict)
    quality_report: dict[str, Any] = field(default_factory=dict)


# -----------------------------------------------------------------------------
# Main extraction functions
# -----------------------------------------------------------------------------


async def extract_entities_from_chunk(
    llm_provider: LLMProvider,
    code: str,
    file_path: str,
    *,
    language: str | None = None,
    start_line: int | None = None,
    end_line: int | None = None,
    chunk_kind: str | None = None,
) -> list[ExtractedEntity]:
    """Extract semantic entities from a code chunk using LLM.

    Args:
        llm_provider: LLM provider for extraction
        code: Source code text
        file_path: Path to the source file

    Returns:
        List of extracted entities
    """
    if not code.strip():
        return []

    prompt = ENTITY_EXTRACTION_PROMPT.format(
        code=code,
        file_path=file_path,
        language=language or "unknown",
        start_line=max(1, int(start_line or 1)),
        end_line=max(1, int(end_line or max(1, code.count("\n") + 1))),
        focus_guidance=_entity_focus_guidance(chunk_kind or _semantic_chunk_kind(file_path)),
    )

    try:
        result = await llm_provider.generate_structured(
            system=ENTITY_EXTRACTION_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
            output_schema=ExtractionResult,
            temperature=0,
            max_tokens=2000,
        )
        return result.entities
    except Exception as e:
        logger.warning("Entity extraction failed for %s: %s", file_path, e)
        return []


async def extract_relationships_from_chunk(
    llm_provider: LLMProvider,
    entities: list[ExtractedEntity],
    code: str,
    *,
    file_path: str = "<unknown>",
    language: str | None = None,
    start_line: int | None = None,
    end_line: int | None = None,
    chunk_kind: str | None = None,
) -> list[ExtractedRelationship]:
    """Extract relationships between entities using LLM.

    Args:
        llm_provider: LLM provider for extraction
        entities: Entities to find relationships between
        code: Source code context

    Returns:
        List of extracted relationships
    """
    if not entities or len(entities) < 2:
        return []

    # Format entities for prompt
    entities_text = "\n".join(f"- {e.name} ({e.type}): {e.description}" for e in entities)

    prompt = RELATIONSHIP_EXTRACTION_PROMPT.format(
        entities=entities_text,
        code=code,
        file_path=file_path,
        language=language or "unknown",
        start_line=max(1, int(start_line or 1)),
        end_line=max(1, int(end_line or max(1, code.count("\n") + 1))),
        relationship_focus=_relationship_focus_guidance(
            chunk_kind or _semantic_chunk_kind(file_path)
        ),
    )

    try:
        result = await llm_provider.generate_structured(
            system=RELATIONSHIP_EXTRACTION_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
            output_schema=ExtractionResult,
            temperature=0,
            max_tokens=1500,
        )
        return result.relationships
    except Exception as e:
        logger.warning("Relationship extraction failed: %s", e)
        return []


def _normalize_repo_path(file_path: str) -> str:
    """Normalize file paths/URIs to a forward-slash repo-relative form."""
    return str(file_path or "").split("?", 1)[0].replace("\\", "/").strip()


def _resolve_chunk_line_range(chunk_meta: Any, chunk_content: str) -> tuple[int, int]:
    """Resolve a chunk's line range from metadata, falling back to content length."""
    start_line = 1
    end_line = max(1, chunk_content.count("\n") + 1)
    if isinstance(chunk_meta, dict):
        meta_start = chunk_meta.get("start_line")
        meta_end = chunk_meta.get("end_line")
        if isinstance(meta_start, int) and meta_start > 0:
            start_line = meta_start
        if isinstance(meta_end, int) and meta_end >= start_line:
            end_line = meta_end
    return start_line, end_line


def _infer_chunk_language(file_path: str, chunk_meta: Any) -> str | None:
    """Infer the chunk language from metadata or file extension."""
    if isinstance(chunk_meta, dict):
        explicit = chunk_meta.get("language")
        if isinstance(explicit, str) and explicit.strip():
            return explicit.strip().lower()

    from contextmine_core.treesitter.languages import detect_language

    detected = detect_language(file_path)
    return detected.value if detected else None


def _semantic_chunk_kind(file_path: str, language: str | None = None) -> str:
    """Classify a chunk for prioritization and prompt shaping."""
    normalized_path = _normalize_repo_path(file_path)
    file_name = Path(normalized_path).name.lower()
    suffixes = [suffix.lower() for suffix in Path(file_name).suffixes]

    if file_name in CONFIG_FILE_NAMES:
        return "config_integration"
    if any(suffix in CONFIG_FILE_SUFFIXES for suffix in suffixes):
        return "config_integration"
    path_parts = {part.lower() for part in normalized_path.split("/") if part}
    if path_parts & CONFIG_PATH_MARKERS:
        return "config_integration"
    if any(suffix in DOCUMENTATION_FILE_SUFFIXES for suffix in suffixes):
        return "documentation"
    if language:
        return "core_code"
    return "unknown"


def _entity_focus_guidance(chunk_kind: str) -> str:
    """Return chunk-kind-specific entity extraction guidance."""
    if chunk_kind == "config_integration":
        return (
            "prefer integrations, deployed services, queues/topics, databases, scheduled jobs, "
            "API surfaces, environment-backed dependencies, and infrastructure roles; "
            "ignore repetitive key/value boilerplate and vendor metadata"
        )
    if chunk_kind == "documentation":
        return (
            "extract only concrete architecture components, workflows, interfaces, or domain models "
            "explicitly described here; ignore generic prose and repository instructions"
        )
    return (
        "prefer business capabilities, architectural components, important data models, workflows, "
        "integrations, and infrastructure roles; ignore tests, mocks, generated code, dependency "
        "code, framework glue, and trivial wrappers; if the chunk contains no durable "
        "architecture/domain concepts, return no entities"
    )


def _relationship_focus_guidance(chunk_kind: str) -> str:
    """Return chunk-kind-specific relationship extraction guidance."""
    if chunk_kind == "config_integration":
        return (
            "prefer ownership, routing, deployment, dependency, messaging, scheduling, and "
            "integration relationships exposed by configuration"
        )
    if chunk_kind == "documentation":
        return "prefer explicit architectural dependencies or workflow transitions described in the text"
    return (
        "prefer durable runtime, dependency, validation, transformation, and ownership "
        "relationships rather than incidental function-level wiring"
    )


def _chunk_priority_tuple(
    file_path: str,
    chunk_index: int,
    start_line: int,
    chunk_kind: str,
) -> tuple[int, int, int, str]:
    """Build a stable priority tuple for semantic extraction ordering."""
    base_rank = {
        "core_code": 0,
        "config_integration": 1,
        "unknown": 2,
        "documentation": 3,
    }.get(chunk_kind, 4)

    normalized_path = _normalize_repo_path(file_path).lower()
    path_penalty = 0
    if any(marker in normalized_path for marker in ("/examples/", "/demo/", "/sample/", "/docs/")):
        path_penalty += 2
    if any(marker in normalized_path for marker in ("/scripts/", "/migrations/", "/fixtures/")):
        path_penalty += 1
    return (base_rank, path_penalty, max(0, int(chunk_index)), normalized_path + f":{start_line}")


def _build_quality_report(
    *,
    total_chunks_loaded: int,
    selected_chunks: int,
    chunk_budget_deferred: int,
    skipped_reasons: dict[str, int],
    chunk_kind_counts: dict[str, int],
    raw_entity_count: int,
    resolved_entity_count: int,
    relationship_count: int,
    unique_source_files: int,
    resolution_audit: dict[str, Any],
) -> dict[str, Any]:
    """Build a machine-readable semantic extraction quality report."""
    warnings: list[str] = []

    if selected_chunks == 0:
        status = "empty"
        warnings.append("no_high_signal_chunks_selected")
    else:
        status = "healthy"
        if resolved_entity_count == 0:
            status = "empty"
            warnings.append("no_semantic_entities_extracted")
        if relationship_count == 0 and resolved_entity_count > 0:
            status = "degraded"
            warnings.append("no_semantic_relationships_extracted")
        if selected_chunks >= 5 and resolved_entity_count / max(selected_chunks, 1) < 0.5:
            status = "degraded"
            warnings.append("low_entity_yield")
        if resolved_entity_count > 0 and relationship_count / max(resolved_entity_count, 1) < 0.2:
            status = "degraded"
            warnings.append("low_relationship_yield")
        if chunk_budget_deferred > 0:
            warnings.append("chunk_budget_applied")
        if resolution_audit.get("incompatible_pairs_blocked", 0) > 0:
            warnings.append("merge_pairs_blocked")
        if resolution_audit.get("suspicious_group_count", 0) > 0:
            status = "degraded"
            warnings.append("suspicious_merge_groups")

    return {
        "status": status,
        "warnings": warnings,
        "total_chunks_loaded": total_chunks_loaded,
        "selected_chunks": selected_chunks,
        "chunk_budget_deferred": chunk_budget_deferred,
        "skipped_reasons": dict(skipped_reasons),
        "chunk_kind_counts": dict(chunk_kind_counts),
        "raw_entity_count": raw_entity_count,
        "resolved_entity_count": resolved_entity_count,
        "relationship_count": relationship_count,
        "unique_source_files": unique_source_files,
        "resolution_audit": dict(resolution_audit),
    }


def _looks_like_test_path(normalized_path: str) -> bool:
    """Return True when the path clearly refers to test-only material."""
    if not normalized_path:
        return False

    parts = [part.lower() for part in normalized_path.split("/") if part]
    if any(part in LOW_SIGNAL_TEST_PATH_PARTS for part in parts):
        return True

    file_name = parts[-1] if parts else normalized_path.lower()
    return (
        file_name.startswith("test_")
        or file_name.endswith("_test.py")
        or file_name.endswith("_spec.py")
        or ".test." in file_name
        or ".spec." in file_name
    )


def _looks_generated_or_minified(content: str) -> bool:
    """Return True when the chunk appears generated, snapshot-based, or minified."""
    sample = content[:2000].lower()
    if any(marker in sample for marker in LOW_SIGNAL_CONTENT_MARKERS):
        return True

    nonempty_lines = [line for line in content.splitlines()[:50] if line.strip()]
    if not nonempty_lines:
        return False

    max_line_length = max(len(line) for line in nonempty_lines)
    avg_line_length = sum(len(line) for line in nonempty_lines) / len(nonempty_lines)
    return max_line_length >= 800 and avg_line_length >= 250


def _should_skip_semantic_chunk(file_path: str, chunk_meta: Any, chunk_content: str) -> str | None:
    """Return a skip reason when a chunk is too low-signal for semantic extraction."""
    normalized_path = _normalize_repo_path(file_path)
    parts = [part.lower() for part in normalized_path.split("/") if part]
    file_name = parts[-1] if parts else normalized_path.lower()

    if isinstance(chunk_meta, dict) and bool(chunk_meta.get("generated")):
        return "generated_meta"
    if any(part in LOW_SIGNAL_REPO_PATH_PARTS for part in parts):
        return "ignored_path"
    if _looks_like_test_path(normalized_path):
        return "test_artifact"
    if any(file_name.endswith(suffix) for suffix in LOW_SIGNAL_FILE_SUFFIXES):
        return "generated_suffix"
    if normalized_path.endswith(
        (".generated.ts", ".generated.tsx", ".generated.js", ".generated.py")
    ):
        return "generated_suffix"
    if _looks_generated_or_minified(chunk_content):
        return "generated_content"
    return None


async def extract_from_documents(
    collection_id: UUID,
    llm_provider: LLMProvider,
    embedder: Any,
    max_chunks: int | None = None,
    similarity_threshold: float = 0.85,
    changed_doc_ids: list[str] | None = None,
) -> ExtractionBatch:
    """Extract entities and relationships from documents in a collection.

    Implements full GraphRAG extraction including:
    1. Per-document entity extraction (LLM)
    2. Per-document relationship extraction (LLM)
    3. Entity resolution via embedding similarity (merge semantically similar entities)
    4. Cross-document relationship inference (co-occurrence)

    When ``changed_doc_ids`` is provided, only chunks from those documents are
    processed through the LLM. This dramatically reduces cost on incremental syncs.

    Args:
        collection_id: Collection to process
        llm_provider: LLM provider for extraction
        embedder: Embedding provider for semantic entity resolution. REQUIRED.
                  Uses embedding similarity to merge entities across languages,
                  naming conventions, and synonyms.
        max_chunks: Optional maximum chunks to process. ``None`` processes all chunks.
        similarity_threshold: Cosine similarity threshold for entity merging (0.85 default)
        changed_doc_ids: If provided, only extract from chunks belonging to these
                         document IDs.  Pass ``None`` for a full extraction (initial run).

    Returns:
        ExtractionBatch with all extracted entities and relationships

    Raises:
        ValueError: If embedder is not provided
    """
    if embedder is None:
        raise ValueError(
            "embedder is required for GraphRAG entity extraction. "
            "Entity resolution requires embedding similarity to work across "
            "languages, naming conventions, and synonyms."
        )

    import uuid as uuid_module

    from contextmine_core import get_session
    from contextmine_core.models import Chunk, Document, Source
    from sqlalchemy import select

    batch = ExtractionBatch()

    # Load pre-split chunks instead of whole documents.  Documents can be
    # much larger than an LLM context window; the Chunk table already
    # contains retrieval-sized pieces, so we use those directly.
    # When changed_doc_ids is provided, scope to only those documents.
    async with get_session() as session:
        stmt = (
            select(
                Chunk.id,
                Chunk.document_id,
                Chunk.content,
                Chunk.meta,
                Document.uri,
                Chunk.chunk_index,
            )
            .join(Document, Chunk.document_id == Document.id)
            .join(Source, Document.source_id == Source.id)
            .where(Source.collection_id == collection_id)
        )
        if changed_doc_ids:
            changed_uuids = [uuid_module.UUID(d) for d in changed_doc_ids]
            stmt = stmt.where(Chunk.document_id.in_(changed_uuids))
        stmt = stmt.order_by(Document.uri, Chunk.chunk_index)
        result = await session.execute(stmt)
        chunks = result.all()

    all_entities: list[ExtractedEntity] = []
    raw_entity_evidence: dict[str, list[EntityEvidenceRecord]] = {}
    skipped_low_signal = 0
    skipped_reasons: dict[str, int] = {}
    chunk_kind_counts: dict[str, int] = {}
    candidates: list[tuple[tuple[int, int, int, str], Any]] = []

    # Accumulate per-document entities for cross-doc relationship inference.
    # Multiple chunks may belong to the same document.
    doc_entities: dict[str, list[str]] = {}

    for chunk_id, _doc_id, chunk_content, chunk_meta, doc_uri_raw, chunk_index in chunks:
        if not chunk_content or not chunk_content.strip():
            continue

        doc_uri = doc_uri_raw or str(_doc_id)
        skip_reason = _should_skip_semantic_chunk(doc_uri, chunk_meta, chunk_content)
        if skip_reason:
            skipped_low_signal += 1
            skipped_reasons[skip_reason] = skipped_reasons.get(skip_reason, 0) + 1
            logger.debug("Skipping semantic extraction for %s (%s)", doc_uri, skip_reason)
            continue

        start_line, end_line = _resolve_chunk_line_range(chunk_meta, chunk_content)
        language = _infer_chunk_language(doc_uri, chunk_meta)
        chunk_kind = _semantic_chunk_kind(doc_uri, language)
        chunk_kind_counts[chunk_kind] = chunk_kind_counts.get(chunk_kind, 0) + 1
        candidates.append(
            (
                _chunk_priority_tuple(doc_uri, int(chunk_index or 0), start_line, chunk_kind),
                (
                    chunk_id,
                    doc_uri,
                    chunk_content,
                    start_line,
                    end_line,
                    language,
                    chunk_kind,
                ),
            )
        )

    candidates.sort(key=lambda item: item[0])
    if max_chunks is not None and max_chunks > 0:
        selected_candidates = candidates[:max_chunks]
    else:
        selected_candidates = candidates
    chunk_budget_deferred = max(0, len(candidates) - len(selected_candidates))

    for _priority, (
        chunk_id,
        doc_uri,
        chunk_content,
        start_line,
        end_line,
        language,
        chunk_kind,
    ) in selected_candidates:
        entities = await extract_entities_from_chunk(
            llm_provider=llm_provider,
            code=chunk_content,
            file_path=doc_uri,
            language=language,
            start_line=start_line,
            end_line=end_line,
            chunk_kind=chunk_kind,
        )

        if entities:
            for entity in entities:
                entity.source_files.append(doc_uri)
                raw_entity_evidence.setdefault(entity.name.lower(), []).append(
                    EntityEvidenceRecord(
                        file_path=doc_uri,
                        chunk_id=chunk_id,
                        start_line=start_line,
                        end_line=end_line,
                        snippet=chunk_content[:500],
                    )
                )

            doc_entities.setdefault(doc_uri, []).extend(e.name for e in entities)
            all_entities.extend(entities)

            # Extract relationships within this chunk
            relationships = await extract_relationships_from_chunk(
                llm_provider=llm_provider,
                entities=entities,
                code=chunk_content,
                file_path=doc_uri,
                language=language,
                start_line=start_line,
                end_line=end_line,
                chunk_kind=chunk_kind,
            )

            for rel in relationships:
                batch.relationships.append(
                    SemanticRelationship(
                        source_entity=rel.source,
                        target_entity=rel.target,
                        relationship_type=rel.relationship,
                        description=rel.description,
                        strength=rel.strength,
                    )
                )

        batch.chunks_processed += 1

    batch.entity_occurrences = doc_entities

    # Resolve and merge entities across documents using embedding similarity
    # This handles multi-language, naming conventions, abbreviations, synonyms
    batch.entities, resolution_audit = await _resolve_entities_with_embeddings_audited(
        all_entities, embedder, similarity_threshold
    )
    name_to_resolved = _build_entity_name_resolver(batch.entities)
    batch.relationships = _canonicalize_relationships(batch.relationships, name_to_resolved)
    resolved_evidence: dict[str, list[EntityEvidenceRecord]] = {}
    for raw_name, records in raw_entity_evidence.items():
        resolved_name = name_to_resolved.get(raw_name)
        if not resolved_name:
            continue
        bucket = resolved_evidence.setdefault(resolved_name.lower(), [])
        seen = {(r.file_path, r.chunk_id, r.start_line, r.end_line, r.snippet) for r in bucket}
        for record in records:
            key = (
                record.file_path,
                record.chunk_id,
                record.start_line,
                record.end_line,
                record.snippet,
            )
            if key not in seen:
                bucket.append(record)
                seen.add(key)
    batch.entity_evidence = resolved_evidence
    batch.quality_report = _build_quality_report(
        total_chunks_loaded=len(chunks),
        selected_chunks=batch.chunks_processed,
        chunk_budget_deferred=chunk_budget_deferred,
        skipped_reasons=skipped_reasons,
        chunk_kind_counts=chunk_kind_counts,
        raw_entity_count=len(all_entities),
        resolved_entity_count=len(batch.entities),
        relationship_count=len(batch.relationships),
        unique_source_files=len(
            {record.file_path for records in resolved_evidence.values() for record in records}
        ),
        resolution_audit=resolution_audit,
    )
    logger.info(
        "Entity resolution: %d entities merged to %d using embedding similarity (threshold=%.2f)",
        len(all_entities),
        len(batch.entities),
        similarity_threshold,
    )

    # Create cross-document relationships based on co-occurrence
    # Entities that appear in the same document are implicitly related
    cross_doc_relationships = _extract_cross_document_relationships(
        batch.entities,
        batch.entity_occurrences,
        batch.relationships,
    )
    batch.relationships.extend(cross_doc_relationships)

    logger.info(
        "Extracted %d entities, %d relationships (%d cross-doc) from %d chunks (%d skipped low-signal)",
        len(batch.entities),
        len(batch.relationships),
        len(cross_doc_relationships),
        batch.chunks_processed,
        skipped_low_signal,
    )

    return batch


async def _get_entity_embeddings(embedder: Any, embed_texts: list[str]) -> list:
    """Get embeddings from the embedder, supporting both modern and legacy APIs."""
    if hasattr(embedder, "embed_batch"):
        batch = await embedder.embed_batch(embed_texts)
        embeddings = list(getattr(batch, "embeddings", []) or [])
    elif hasattr(embedder, "embed_texts"):
        embeddings = list(await embedder.embed_texts(embed_texts))
    else:
        raise ValueError(
            "embedder must implement embed_batch(texts) or embed_texts(texts) for entity resolution"
        )
    if not embeddings:
        raise ValueError("embedder returned no embeddings for entity resolution")
    return embeddings


async def _resolve_entities_with_embeddings_audited(
    entities: list[ExtractedEntity],
    embedder: Any,
    similarity_threshold: float = 0.85,
) -> tuple[list[SemanticEntity], dict[str, Any]]:
    """Resolve entities and return an audit summary for suspicious merge behavior."""
    import numpy as np

    if not entities:
        return [], {
            "input_entities": 0,
            "resolved_entities": 0,
            "merged_groups": 0,
            "max_group_size": 0,
            "incompatible_pairs_blocked": 0,
            "suspicious_group_count": 0,
            "suspicious_groups": [],
        }

    embed_texts = [f"{e.name}: {e.description}" for e in entities]
    embeddings = await _get_entity_embeddings(embedder, embed_texts)
    embeddings_array = np.array(embeddings)

    norms = np.linalg.norm(embeddings_array, axis=1, keepdims=True)
    norms[norms == 0] = 1
    normalized = embeddings_array / norms
    similarity_matrix = np.dot(normalized, normalized.T)

    parent = list(range(len(entities)))
    incompatible_pairs_blocked = 0

    def find(x: int) -> int:
        if parent[x] != x:
            parent[x] = find(parent[x])
        return parent[x]

    def union(x: int, y: int) -> None:
        px, py = find(x), find(y)
        if px != py:
            parent[px] = py

    for i in range(len(entities)):
        for j in range(i + 1, len(entities)):
            if similarity_matrix[i, j] < similarity_threshold:
                continue
            if _entity_types_compatible(entities[i].type, entities[j].type):
                union(i, j)
            else:
                incompatible_pairs_blocked += 1

    groups: dict[int, list[ExtractedEntity]] = {}
    for idx, entity in enumerate(entities):
        root = find(idx)
        groups.setdefault(root, []).append(entity)

    suspicious_groups: list[dict[str, Any]] = []
    for group in groups.values():
        if len(group) <= 1:
            continue
        type_names = sorted({str(item.type or "OTHER").upper() for item in group})
        if len(group) >= 4 or len([t for t in type_names if t != "OTHER"]) >= 2:
            suspicious_groups.append(
                {
                    "size": len(group),
                    "types": type_names,
                    "sample_names": [item.name for item in group[:5]],
                }
            )

    merged = _merge_entity_groups(groups)
    audit = {
        "input_entities": len(entities),
        "resolved_entities": len(merged),
        "merged_groups": sum(1 for group in groups.values() if len(group) > 1),
        "max_group_size": max((len(group) for group in groups.values()), default=0),
        "incompatible_pairs_blocked": incompatible_pairs_blocked,
        "suspicious_group_count": len(suspicious_groups),
        "suspicious_groups": suspicious_groups[:10],
    }
    return merged, audit


async def _resolve_entities_with_embeddings(
    entities: list[ExtractedEntity],
    embedder: Any,
    similarity_threshold: float = 0.85,
) -> list[SemanticEntity]:
    """Resolve and merge similar entities using embedding similarity.

    This is the proper GraphRAG entity resolution that works across:
    - Different languages (User vs Benutzer vs Usuario)
    - Different naming conventions (user_auth vs UserAuth)
    - Abbreviations (auth vs authentication)
    - Synonyms (customer vs client vs user)

    Args:
        entities: Raw extracted entities
        embedder: Embedding provider with ``embed_batch()`` or ``embed_texts()``
        similarity_threshold: Cosine similarity threshold for merging (0.85 = very similar)

    Returns:
        Deduplicated and merged semantic entities
    """
    merged, _audit = await _resolve_entities_with_embeddings_audited(
        entities,
        embedder,
        similarity_threshold,
    )
    return merged


def _merge_entity_groups(groups: dict[int, list[ExtractedEntity]]) -> list[SemanticEntity]:
    """Merge grouped entities into single SemanticEntity instances."""
    merged: list[SemanticEntity] = []

    for group in groups.values():
        if not group:
            continue

        # Pick the most descriptive name (longest description = most context)
        best_name = max(group, key=lambda e: len(e.description)).name

        # Merge all data from the group
        all_aliases: set[str] = set()
        all_symbols: set[str] = set()
        all_files: set[str] = set()
        descriptions: list[str] = []
        types: list[str] = []

        for entity in group:
            all_aliases.update(entity.aliases)
            all_aliases.add(entity.name)  # Original name becomes alias
            all_symbols.update(entity.source_symbols)
            all_files.update(entity.source_files)
            descriptions.append(entity.description)
            types.append(entity.type)

        # Pick most common type
        type_counts: dict[str, int] = {}
        for t in types:
            type_counts[t] = type_counts.get(t, 0) + 1
        best_type = max(type_counts.keys(), key=lambda t, type_counts=type_counts: type_counts[t])

        # Merge descriptions - take the longest (most detailed)
        merged_desc = descriptions[0] if descriptions else ""
        if len(descriptions) > 1:
            merged_desc = max(descriptions, key=len)

        # Generate stable ID from canonical name
        canonical = best_name.lower().strip()
        entity_id = hashlib.sha256(canonical.encode()).hexdigest()[:16]

        merged.append(
            SemanticEntity(
                id=entity_id,
                name=best_name,
                entity_type=best_type,
                description=merged_desc,
                aliases=list(all_aliases - {best_name}),
                source_symbols=list(all_symbols),
                source_files=list(all_files),
            )
        )

    return merged


def _entity_types_compatible(left: str, right: str) -> bool:
    """Return True when two extracted entity types are safe to merge."""
    lhs = str(left or "OTHER").strip().upper() or "OTHER"
    rhs = str(right or "OTHER").strip().upper() or "OTHER"
    if lhs == rhs:
        return True
    if "OTHER" in {lhs, rhs}:
        return True
    return {lhs, rhs} == {"COMPONENT", "SERVICE"}


def _build_entity_name_resolver(
    resolved_entities: list[SemanticEntity],
) -> dict[str, str]:
    """Build a lowercase name/alias -> canonical entity name mapping."""
    name_to_resolved: dict[str, str] = {}
    for entity in resolved_entities:
        name_to_resolved[entity.name.lower()] = entity.name
        for alias in entity.aliases:
            name_to_resolved[alias.lower()] = entity.name
    return name_to_resolved


def _build_existing_pairs(
    existing_relationships: list[SemanticRelationship],
) -> set[tuple[str, str]]:
    """Build a bidirectional set of existing relationship pairs (lowercase)."""
    pairs: set[tuple[str, str]] = set()
    for rel in existing_relationships:
        src, tgt = rel.source_entity.lower(), rel.target_entity.lower()
        pairs.add((src, tgt))
        pairs.add((tgt, src))
    return pairs


def _canonicalize_relationships(
    relationships: list[SemanticRelationship],
    name_to_resolved: dict[str, str],
) -> list[SemanticRelationship]:
    """Remap extracted relationships onto canonical entity names."""
    canonical: dict[tuple[str, str, str], SemanticRelationship] = {}

    for rel in relationships:
        source = name_to_resolved.get(rel.source_entity.lower())
        target = name_to_resolved.get(rel.target_entity.lower())
        if not source or not target or source == target:
            continue

        key = (source.lower(), target.lower(), rel.relationship_type.upper())
        candidate = SemanticRelationship(
            source_entity=source,
            target_entity=target,
            relationship_type=rel.relationship_type,
            description=rel.description,
            strength=rel.strength,
        )
        current = canonical.get(key)
        if current is None:
            canonical[key] = candidate
            continue
        if float(candidate.strength) > float(current.strength):
            canonical[key] = candidate
            continue
        if float(candidate.strength) == float(current.strength) and len(
            candidate.description
        ) > len(current.description):
            canonical[key] = candidate

    return list(canonical.values())


def _co_occurrence_strength(count: int) -> float:
    """Calculate relationship strength from co-occurrence count."""
    if count >= 5:
        return 0.8
    if count >= 3:
        return 0.6
    if count >= 2:
        return 0.5
    return 0.3


def _accumulate_co_occurrences(
    entity_occurrences: dict[str, list[str]],
    name_to_resolved: dict[str, str],
    existing_pairs: set[tuple[str, str]],
) -> tuple[dict[tuple[str, str], int], dict[tuple[str, str], list[str]]]:
    """Accumulate entity co-occurrence counts and associated documents."""
    co_occurrence: dict[tuple[str, str], int] = {}
    co_occurrence_docs: dict[tuple[str, str], list[str]] = {}

    for doc_uri, original_names in entity_occurrences.items():
        resolved_names = {
            name_to_resolved[orig.lower()]
            for orig in original_names
            if orig.lower() in name_to_resolved
        }
        resolved_list = sorted(resolved_names)
        for i, entity_a in enumerate(resolved_list):
            for entity_b in resolved_list[i + 1 :]:
                pair = (entity_a, entity_b) if entity_a < entity_b else (entity_b, entity_a)
                if (entity_a.lower(), entity_b.lower()) in existing_pairs:
                    continue
                co_occurrence[pair] = co_occurrence.get(pair, 0) + 1
                co_occurrence_docs.setdefault(pair, []).append(doc_uri)

    return co_occurrence, co_occurrence_docs


def _format_doc_summary(doc_list: list[str]) -> str:
    """Format a document list into a summary string."""
    summary = ", ".join(doc_list[:3])
    if len(doc_list) > 3:
        summary += f" +{len(doc_list) - 3} more"
    return summary


def _extract_cross_document_relationships(
    resolved_entities: list[SemanticEntity],
    entity_occurrences: dict[str, list[str]],
    existing_relationships: list[SemanticRelationship],
) -> list[SemanticRelationship]:
    """Extract relationships between entities that co-occur across documents."""
    name_to_resolved = _build_entity_name_resolver(resolved_entities)
    existing_pairs = _build_existing_pairs(existing_relationships)
    co_occurrence, co_occurrence_docs = _accumulate_co_occurrences(
        entity_occurrences,
        name_to_resolved,
        existing_pairs,
    )

    relationships: list[SemanticRelationship] = []
    for (entity_a, entity_b), count in co_occurrence.items():
        doc_list = co_occurrence_docs.get((entity_a, entity_b), [])
        relationships.append(
            SemanticRelationship(
                source_entity=entity_a,
                target_entity=entity_b,
                relationship_type="CO_OCCURS",
                description=f"Co-occur in {count} document(s): {_format_doc_summary(doc_list)}",
                strength=_co_occurrence_strength(count),
            )
        )
    return relationships


# -----------------------------------------------------------------------------
# Persistence functions
# -----------------------------------------------------------------------------


def _create_file_mention_edges(
    session: Any,
    collection_id: UUID,
    entity_name_to_id: dict[str, UUID],
    entity_source_files: dict[str, list[str]],
    file_node_by_uri: dict[str, UUID],
    edge_cls: Any,
    edge_kind_cls: Any,
    stats: dict,
) -> None:
    """Create FILE_MENTIONS_ENTITY edges for graph connectivity."""
    created: set[tuple[UUID, UUID]] = set()
    for entity_name, entity_id in entity_name_to_id.items():
        for uri in entity_source_files.get(entity_name, []):
            file_id = file_node_by_uri.get(uri)
            if not file_id or (file_id, entity_id) in created:
                continue
            session.add(
                edge_cls(
                    collection_id=collection_id,
                    source_node_id=file_id,
                    target_node_id=entity_id,
                    kind=edge_kind_cls.FILE_MENTIONS_ENTITY,
                    meta={"source_uri": uri},
                )
            )
            created.add((file_id, entity_id))
            stats["file_edges_created"] += 1


def _file_node_lookup_keys(natural_key: str) -> set[str]:
    """Return lookup keys for a FILE node natural key.

    The knowledge graph currently contains a mix of legacy ``file:...`` keys
    and plain document URIs. Semantic connectivity must work with both.
    """
    cleaned = str(natural_key or "").strip()
    if not cleaned:
        return set()

    keys = {cleaned}
    if cleaned.startswith("file:"):
        stripped = cleaned.split(":", 1)[1].strip()
        if stripped:
            keys.add(stripped)
    return keys


async def persist_semantic_entities(
    session: AsyncSession,
    collection_id: UUID,
    batch: ExtractionBatch,
    changed_doc_ids: list[str] | None = None,
) -> dict:
    """Persist extracted entities and relationships to the knowledge graph.

    Creates SEMANTIC_ENTITY nodes, SEMANTIC_RELATIONSHIP edges, and
    FILE_MENTIONS_ENTITY edges to connect semantic entities to their
    source files (for graph connectivity in retrieval).

    When ``changed_doc_ids`` is provided, only entities whose evidence
    references those documents are deleted before re-creation.  Entities
    from unchanged documents are preserved.

    Args:
        session: Database session
        collection_id: Collection UUID
        batch: Extraction batch to persist
        changed_doc_ids: Scope deletion to entities linked to these docs.
                         ``None`` deletes all entities (full rebuild).

    Returns:
        Stats dict
    """
    import uuid as uuid_module

    from contextmine_core.models import (
        Chunk,
        KnowledgeEdge,
        KnowledgeEdgeKind,
        KnowledgeEvidence,
        KnowledgeNode,
        KnowledgeNodeEvidence,
        KnowledgeNodeKind,
    )
    from sqlalchemy import delete, select

    stats = {
        "entities_created": 0,
        "relationships_created": 0,
        "file_edges_created": 0,
        "evidence_created": 0,
    }

    # Delete existing semantic entities — scoped to changed docs when possible
    if changed_doc_ids:
        # Only remove entities whose evidence references changed documents
        changed_uuids = [uuid_module.UUID(d) for d in changed_doc_ids]
        stale_q = (
            select(KnowledgeNode.id)
            .join(KnowledgeNodeEvidence, KnowledgeNodeEvidence.node_id == KnowledgeNode.id)
            .join(KnowledgeEvidence, KnowledgeNodeEvidence.evidence_id == KnowledgeEvidence.id)
            .join(Chunk, KnowledgeEvidence.chunk_id == Chunk.id)
            .where(
                KnowledgeNode.collection_id == collection_id,
                KnowledgeNode.kind == KnowledgeNodeKind.SEMANTIC_ENTITY,
                Chunk.document_id.in_(changed_uuids),
            )
            .distinct()
        )
        existing = await session.execute(stale_q)
        existing_ids = [row[0] for row in existing.fetchall()]
    else:
        # Full rebuild: delete all semantic entities for this collection
        existing = await session.execute(
            select(KnowledgeNode.id).where(
                KnowledgeNode.collection_id == collection_id,
                KnowledgeNode.kind == KnowledgeNodeKind.SEMANTIC_ENTITY,
            )
        )
        existing_ids = [row[0] for row in existing.fetchall()]

    if existing_ids:
        await session.execute(
            delete(KnowledgeEdge).where(
                KnowledgeEdge.source_node_id.in_(existing_ids)
                | KnowledgeEdge.target_node_id.in_(existing_ids)
            )
        )
        await session.execute(delete(KnowledgeNode).where(KnowledgeNode.id.in_(existing_ids)))

    # Build lookup of FILE nodes by URI for graph connectivity
    # This enables neighborhood traversal from search results to semantic entities
    file_result = await session.execute(
        select(KnowledgeNode.id, KnowledgeNode.natural_key).where(
            KnowledgeNode.collection_id == collection_id,
            KnowledgeNode.kind == KnowledgeNodeKind.FILE,
        )
    )
    file_node_by_uri: dict[str, UUID] = {}
    for node_id, natural_key in file_result.all():
        for lookup_key in _file_node_lookup_keys(natural_key):
            file_node_by_uri[lookup_key] = node_id

    # Create entity nodes
    entity_name_to_id: dict[str, UUID] = {}
    entity_source_files: dict[str, list[str]] = {}  # entity_name -> list of source URIs

    for entity in batch.entities:
        node = KnowledgeNode(
            collection_id=collection_id,
            kind=KnowledgeNodeKind.SEMANTIC_ENTITY,
            natural_key=entity.natural_key,
            name=entity.name,
            meta={
                "type": entity.entity_type,
                "description": entity.description,
                "aliases": entity.aliases,
                "source_symbols": entity.source_symbols,
                "source_files": entity.source_files,
            },
        )
        session.add(node)
        await session.flush()
        entity_name_to_id[entity.name.lower()] = node.id
        # Track source files for this entity
        entity_source_files[entity.name.lower()] = list(entity.source_files)
        for record in batch.entity_evidence.get(entity.name.lower(), []):
            evidence = KnowledgeEvidence(
                chunk_id=record.chunk_id,
                file_path=record.file_path,
                start_line=max(1, record.start_line),
                end_line=max(1, max(record.start_line, record.end_line)),
                snippet=record.snippet,
            )
            session.add(evidence)
            await session.flush()
            session.add(KnowledgeNodeEvidence(node_id=node.id, evidence_id=evidence.id))
            stats["evidence_created"] += 1
        stats["entities_created"] += 1

    # Create semantic relationship edges
    for rel in batch.relationships:
        source_id = entity_name_to_id.get(rel.source_entity.lower())
        target_id = entity_name_to_id.get(rel.target_entity.lower())

        if not source_id or not target_id:
            continue

        edge = KnowledgeEdge(
            collection_id=collection_id,
            source_node_id=source_id,
            target_node_id=target_id,
            kind=KnowledgeEdgeKind.SEMANTIC_RELATIONSHIP,
            meta={
                "relationship_type": rel.relationship_type,
                "description": rel.description,
                "strength": rel.strength,
            },
        )
        session.add(edge)
        stats["relationships_created"] += 1

    # Create FILE_MENTIONS_ENTITY edges to connect the code graph to semantic graph
    _create_file_mention_edges(
        session,
        collection_id,
        entity_name_to_id,
        entity_source_files,
        file_node_by_uri,
        KnowledgeEdge,
        KnowledgeEdgeKind,
        stats,
    )

    logger.info(
        "Persisted %d entities, %d relationships, %d file edges",
        stats["entities_created"],
        stats["relationships_created"],
        stats["file_edges_created"],
    )

    return stats
