"""Research agent actions."""

from contextmine_core.research.actions.finalize import (
    FinalizeAction,
    format_answer_with_citations,
)
from contextmine_core.research.actions.graph import (
    GraphExpandAction,
    GraphPackAction,
    GraphTraceAction,
    MockGraphExpandAction,
    MockGraphPackAction,
    MockGraphTraceAction,
)
from contextmine_core.research.actions.lsp import (
    LspDefinitionAction,
    LspDiagnosticsAction,
    LspHoverAction,
    LspReferencesAction,
    MockLspDefinitionAction,
)
from contextmine_core.research.actions.open_span import OpenSpanAction
from contextmine_core.research.actions.registry import (
    Action,
    ActionRegistry,
    ActionResult,
    get_action_registry,
    reset_action_registry,
)
from contextmine_core.research.actions.schemas import (
    ActionSelection,
    AgentState,
    FinalizeInput,
    FinalizeOutput,
    GraphEdge,
    GraphExpandInput,
    GraphExpandOutput,
    GraphNode,
    GraphPackedNode,
    GraphPackInput,
    GraphPackOutput,
    GraphPathStep,
    GraphTraceInput,
    GraphTraceOutput,
    HybridSearchInput,
    HybridSearchOutput,
    LspDefinitionOutput,
    LspDiagnostic,
    LspDiagnosticsInput,
    LspDiagnosticsOutput,
    LspHoverOutput,
    LspLocation,
    LspPositionInput,
    LspReferencesOutput,
    OpenSpanInput,
    OpenSpanOutput,
    SearchResult,
    SummarizeEvidenceInput,
    SummarizeEvidenceOutput,
    TsEnclosingSymbolInput,
    TsEnclosingSymbolOutput,
    TsFindSymbolInput,
    TsFindSymbolOutput,
    TsOutlineInput,
    TsOutlineOutput,
    TsSymbol,
)
from contextmine_core.research.actions.search import (
    HybridSearchAction,
    MockHybridSearchAction,
)
from contextmine_core.research.actions.summarize import (
    MockSummarizeAction,
    SummarizeEvidenceAction,
)
from contextmine_core.research.actions.treesitter import (
    MockTsFindSymbolAction,
    MockTsOutlineAction,
    TsEnclosingSymbolAction,
    TsFindSymbolAction,
    TsOutlineAction,
)

__all__ = [
    # Registry
    "Action",
    "ActionRegistry",
    "ActionResult",
    "get_action_registry",
    "reset_action_registry",
    # Schemas
    "ActionSelection",
    "AgentState",
    "FinalizeInput",
    "FinalizeOutput",
    "HybridSearchInput",
    "HybridSearchOutput",
    "LspDefinitionOutput",
    "LspDiagnostic",
    "LspDiagnosticsInput",
    "LspDiagnosticsOutput",
    "LspHoverOutput",
    "LspLocation",
    "LspPositionInput",
    "LspReferencesOutput",
    "OpenSpanInput",
    "OpenSpanOutput",
    "SearchResult",
    "SummarizeEvidenceInput",
    "SummarizeEvidenceOutput",
    "TsEnclosingSymbolInput",
    "TsEnclosingSymbolOutput",
    "TsFindSymbolInput",
    "TsFindSymbolOutput",
    "TsOutlineInput",
    "TsOutlineOutput",
    "TsSymbol",
    # Graph Schemas
    "GraphEdge",
    "GraphExpandInput",
    "GraphExpandOutput",
    "GraphNode",
    "GraphPackedNode",
    "GraphPackInput",
    "GraphPackOutput",
    "GraphPathStep",
    "GraphTraceInput",
    "GraphTraceOutput",
    # Actions
    "FinalizeAction",
    "GraphExpandAction",
    "GraphPackAction",
    "GraphTraceAction",
    "HybridSearchAction",
    "LspDefinitionAction",
    "LspDiagnosticsAction",
    "LspHoverAction",
    "LspReferencesAction",
    "MockGraphExpandAction",
    "MockGraphPackAction",
    "MockGraphTraceAction",
    "MockHybridSearchAction",
    "MockLspDefinitionAction",
    "MockSummarizeAction",
    "MockTsFindSymbolAction",
    "MockTsOutlineAction",
    "OpenSpanAction",
    "SummarizeEvidenceAction",
    "TsEnclosingSymbolAction",
    "TsFindSymbolAction",
    "TsOutlineAction",
    # Utilities
    "format_answer_with_citations",
]
